import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import PopupNotification from "@/components/PopupNotification";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PopupNotification />

        <div className="flex flex-col h-screen w-screen">
          <div className="sticky top-0 w-full z-10 h-fit">
            <Header />
          </div>
          <div className="w-full flex h-[calc(100%-56px)]">
            <div className="h-full sticky top-[56px] w-fit">
              <Sidebar />
            </div>

            {children}
          </div>
        </div>

      </body>
      {/* <body className={inter.className}>{children}</body> */}
    </html>
  );
}
